name: ${PROJECT_NAME}

services:
  mongo_db:
    image: mongo:6.0
    container_name: ${MONGO_CONTAINER_NAME}
    restart: always
    volumes:
      - ../notaria_data_log/notaria_mongo-vol:/data/db
    ports:
      - "27015:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ['--auth']

  api_service:
    build:
      context: .
      dockerfile: Dockerfile-native
      args:
        DOCKER_BUILDKIT: 1
        API_IMAGE_NAME: ${API_IMAGE_NAME}
    image: frix/${API_IMAGE_NAME}:latest
    container_name: ${API_CONTAINER_NAME}
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      APP_PATH: ${APP_PATH}
      APP_SHOW_LOG: ${APP_SHOW_LOG}
      APP_SHOW_DOCS: ${APP_SHOW_DOCS}
      APP_HOST_ORIGIN: ${APP_HOST_ORIGIN}
      NGROK_ENABLED: ${NGROK_ENABLED}
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
      APP_SECURITY_USERNAME: ${APP_SECURITY_USERNAME}
      APP_SECURITY_PASSWORD: ${APP_SECURITY_PASSWORD}
      MONGO_URL_DOCKER: ${MONGO_URL_DOCKER}
    depends_on:
      mongo_db:
        condition: service_started

# solo necesario cuando es gestionado por docker
#volumes:
#  mapa_mongo-vol:
#    external: false
