FROM ghcr.io/graalvm/native-image-community:22.0.2-muslib AS build

# Install necessary tools (if any)
RUN microdnf install wget xz

# Intall maven
#RUN wget https://dlcdn.apache.org/maven/maven-3/3.9.8/binaries/apache-maven-3.9.8-bin.tar.gz
#RUN tar xvf apache-maven-3.9.8-bin.tar.gz
#ENV M2_HOME=/app/apache-maven-3.9.8
#ENV M2=$M2_HOME/bin
#ENV PATH=$M2:$PATH

# Install UPX
RUN wget https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-amd64_linux.tar.xz
RUN tar xvf upx-4.2.4-amd64_linux.tar.xz
ENV UPX_HOME=/app/upx-4.2.4-amd64_linux
ENV PATH=$UPX_HOME:$PATH

# Copy source and maven (not install)
RUN mkdir -p /app/rest-api-app
COPY mvnw /app/rest-api-app/mvnw
COPY .mvn /app/rest-api-app/.mvn
COPY pom.xml /app/rest-api-app/pom.xml
COPY src /app/rest-api-app/src

ARG API_IMAGE_NAME
WORKDIR /app/rest-api-app
RUN ./mvnw -Pnative native:compile
RUN upx -7 -k /app/rest-api-app/target/${API_IMAGE_NAME}

FROM amd64/alpine:3.17
WORKDIR /app
ARG API_IMAGE_NAME
COPY --from=build /app/rest-api-app/target/${API_IMAGE_NAME} .
RUN ls -l /app
EXPOSE 8080
ENTRYPOINT ["/app/demo_notaria_mapa"]
